### ISSUE TITLE
MobsDropAttackUpItems false disables exp gain

### ISSUE THREAD

**Issue by ghost** [PaulAnthonyReitz/ReitzMMO#23]
MobsDropAttackUpItems disables exp gain completely when it is set to false.

A workaround is to set the chance to 0.

```
General:
  MobsDropAttackUpItems:
    Enabled: true
    PercentChance: 0
```

Tested on Paper version git-Paper-105 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT).

Original Message:

Hello, since I updated to 1.17 Hotfix 3 my players are unable to earn combat EXP. Was something changed or is it a bug in my configuration?

PlayerConfig.yml
```
# This config is used to set all monster health related configurations
BossBar:
  Enabled: false
Scaling:
  World:
    WorldBaseCombatEXP:
      Base: 25
      Multiplier: 2
  Player:
    HealthScale: 1
    AttackScale: 1
    DefenseScale: 1
```
